### ISSUE TITLE
Deprecation warning when using PHP 8.1

### ISSUE THREAD

**Issue by felipeEddy** [stripe/stripe-php#1237]
There are new rules with the PHP 8.1 update, some fixes must be done in order to prevent errors and warnings. Example below:

![image](https://user-images.githubusercontent.com/49731840/151442149-0b98ed22-e4ed-4cf6-89ac-f8fdddac43d0.png)

I'm current using version **v7.112.0**.

**Comment by benhath** [comment]
2.4.4 supports PHP 8.1 - setup:upgrade fails with:

Unable to apply data patch StripeIntegration\Payments\Setup\Patch\Data\Patch001WebhooksConfiguration for module StripeIntegration_Payments. Original exception message: Deprecated Functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /Users/***/Development/dev.local/vendor/stripe/module-payments/Model/Config.php on line 295

```php
    public function decrypt($key)
    {
         if (!preg_match('/^[A-Za-z0-9_]+$/', $key))
            $key = $this->encryptor->decrypt($key);

        return trim($key);
    }
```

**Comment by SachinBahukhandi** [comment]
Are PR's being accepted on this?

**Comment by dcr-stripe** [comment]
Hi @felipeEddy , thank you for the report here. I'd love to get these warnings resolved. How are they surfacing for you? This particular case is only possible if calling the magic `__debugInfo()` method on a RequestOptions object (eg. by using `var_dump`) which does not have an API key set. I can do an isolated fix for this, but I'd like to make sure these warnings are all resolved and not just this one.

**Comment by moonbas3** [comment]
Hey @dcr-stripe, simply loading the bindings in an 8.1 environment will spit out a lot of notices that need to be taken care of. Here are some other examples:

`[15-Jun-2022 06:29:06 UTC] PHP Deprecated:  Return type of Stripe\StripeObject::offsetGet($k) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /mnt/.../stripe/libs/stripe/lib/StripeObject.php on line 215
[15-Jun-2022 06:29:06 UTC] PHP Deprecated:  Return type of Stripe\StripeObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /mnt/.../stripe/libs/stripe/lib/StripeObject.php on line 426`

**Comment by dcr-stripe** [comment]
Which version of stripe-php are you using @moonbas3 ? 

These warnings today should already be suppressed by `#[\ReturnTypeWillChange]` eg. [offsetGet](https://github.com/stripe/stripe-php/blob/0772825acead85d3e02aa1fd93a8f33a906d26d7/lib/StripeObject.php#L216), [jsonSerialize](https://github.com/stripe/stripe-php/blob/0772825acead85d3e02aa1fd93a8f33a906d26d7/lib/StripeObject.php#L432). These suppressions have been present for a while now.

Locally, if I check my PHP version:

```

PHP 8.1.5 (cli) (built: Apr 16 2022 00:14:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
```

and pull in stripe-php v8.7.0 (latest), I don't get these deprecation warnings. I do however get them for other PHP interactions outside of Stripe (eg. with composer, symfony, etc.). So I'm wondering if there's a misconfiguration somewhere 🤔

**Comment by franmomu** [comment]
There is https://github.com/stripe/stripe-php/pull/1273 which should fix the ones coming from `Stripe\StripeObject`.

**Comment by rdnn** [comment]
@dcr-stripe Some are caused by PHP Deprecated and others are caused by User Deprecated (e.g., Symfony).

@franmomu Nice! Any chance PHPDoc blocks for the below functions can be included in your PR?

`count()` in [`Stripe\Util\CaseInsensitiveArray`](https://github.com/stripe/stripe-php/blob/f310ff036d1dd2bd6f8bdf0249d248083c01129f/lib/Util/CaseInsensitiveArray.php#L25)
`offsetGet()` in [`Stripe\Collection`](https://github.com/stripe/stripe-php/blob/eb2c1cee8f23630fc57b60fc573087a8822dc4eb/lib/Collection.php#L54)
`offsetGet()` in [`Stripe\SearchResult`](https://github.com/stripe/stripe-php/blob/58a985a0d2e33ab81078bb7ccfca041c7aabbf69/lib/SearchResult.php#L66)

**Comment by degive** [comment]
Has this issue been resolved because I just pulled v9.5 and still get the errors when running php 8.0:

[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 44
[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 57
[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 34
[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 51
[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 24
[08-Sep-2022 18:47:02 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\CaseInsensitiveArray::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 29
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::offsetExists($k) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 202
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::offsetGet($k) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 212
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::offsetSet($k, $v) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 197
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::offsetUnset($k) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 207
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 218
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\StripeObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/StripeObject.php on line 422
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Collection.php on line 119
[08-Sep-2022 18:47:03 America/Chicago] PHP Deprecated:  Return type of Stripe\Util\Set::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home3/degiveco/public_html/rv/includes/stripe/vendor/stripe/stripe-php/lib/Util/Set.php on line 40

**Comment by adamz01h** [comment]
```
 Deprecated: Return type of Stripe\StripeObject::offsetExists($k) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 202

 Deprecated: Return type of Stripe\StripeObject::offsetGet($k) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 212

 Deprecated: Return type of Stripe\StripeObject::offsetSet($k, $v) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 197


Deprecated: Return type of Stripe\StripeObject::offsetUnset($k) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 207



 Deprecated: Return type of Stripe\StripeObject::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 218

  Deprecated: Return type of Stripe\StripeObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 424


  Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/RequestOptions.php on line 159


   Deprecated: Return type of Stripe\Util\Set::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/Set.php on line 40


   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 44


   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 57

   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 34



   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 51


   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 24


   Deprecated: Return type of Stripe\Util\CaseInsensitiveArray::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Util/CaseInsensitiveArray.php on line 29


    Deprecated: Return type of Stripe\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/Collection.php on line 119

```
same issue using php 8.1

**Comment by degive** [comment]
Any plans on fixing this?

**Comment by richardm-stripe** [comment]
Hello, thank you for writing in @degive and @adamz01h.

I am unable to reproduce the deprecation warnings myself on recent versions of `stripe-php` and my simple example project. Taking a look at the text you have pasted:

> Deprecated: Return type of Stripe\StripeObject::offsetExists($k) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/project/composer/vendor/stripe/stripe-php/lib/StripeObject.php on line 202

This seems to indicate that the `offsetExists` function is on line 202  of `StripeObject.php`. However, that hasn't been the case since [this PR was merged](https://github.com/stripe/stripe-php/pull/1211/files#diff-7754ca6a9be3af0d5b0f5319936b5d05f02f8d91aecc94164bdeb5f40d9f1a00L202) and released in stripe-php v7.104.0, so perhaps somehow in your environment an old version of `stripe-php` is being loaded instead?

Can you double-check the version of `stripe-php`? If composer is misbehaving, perhaps looking at `vendor/stripe/stripe-php/VERSION` is a more robust way to check the version than looking at the `composer.json`.

**Comment by richardm-stripe** [comment]
I'm closing, as I suspect this is an environmental issue.

Please do re-open if you can demonstrate deprecation warnings in the latest version - ideally with a sample project and reproduction steps!

**Comment by degive** [comment]
I downloaded the latest version and it seems to work fine. Thank you!

**Comment by PatrickHeijmans** [comment]
I still have these errors running: PHP 8.1.29
